plugins { id 'com.android.application' }

android {
    namespace 'hr.ifmont.servis'
    compileSdk 35

    defaultConfig {
        applicationId 'hr.ifmont.servis'
        minSdk 29
        targetSdk 35
        versionCode 107
        versionName '10.7'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('ifmont-release.jks')
            storePassword System.getenv('IFMONT_KEYSTORE_PASSWORD')
            keyAlias System.getenv('IFMONT_KEY_ALIAS')
            keyPassword System.getenv('IFMONT_KEY_PASSWORD')
        }
    }

    buildTypes {
        debug { debuggable true }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
